services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .postgres.secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - red-tetrix-network
  
  adminer:
    image: adminer
    ports:
      - 2121:8080
    networks:
      - red-tetrix-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env
      - .postgres.secret
    depends_on:
      - db
    command: npm run srv-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - red-tetrix-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - frontend/.env
    depends_on:
      - backend
    command: npm run client-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - red-tetrix-network
  
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #  - ./certbot/www/:/var/www/certbot/:ro
    #  - ./certbot/conf/:/etc/nginx/ssl/:ro
    container_name: nginx
    ports:
     - 8080:80
     - 4430:443
    depends_on:
      - frontend
    networks:
      - red-tetrix-network
    env_file:
      - .env
  
networks: 
  red-tetrix-network:
    driver: bridge
volumes:
  pgdata:
